version: '3'
services:
  task-app:
    build: .
    restart: always
    ports: 
      - '8080:8080'
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ../../mongodbtest:/data/db