---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: hcausevic5/node-app
        name: nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-env-volume
          mountPath: /usr/src/app/.env
          subPath: .env
      volumes:
      - name: app-env-volume
        configMap:
          name: app-env
